### ISSUE TITLE
Please Restore Collision-Ignorant Building Ability

### ISSUE THREAD

**Issue by SextonKing** [Algalish/SmartFoundationsPublic#31] opened 2020-10-28 12:33 UTC
Your mod was great, but then you removed this ability and claim it was a 'cheat.' It was not. It was a useful function for restoring structures in some areas that already had other items built without having to completely dismantle and lose all that work just to edit a single aspect of a build.

It would be appreciated if you would simply restore this ability. It allowed me to re-floor some crucial sections of my new mega base design, but now I can't finish those since this new update without completely dismantling the entire base, losing hours what would've taken a few minutes now. And if you had solicited feedback on this feature first, I suspect others would've told you this as well.

Without this feature, all that's really left is just another copy-paste mod, and I already have Area Actions and Micro Manage and Quick Foundations for all the features in your app. The one thing your mod really excelled at was simple built-tool-native ease use that allowed me to lay down foundations anywhere including where I crucially needed them to correct earlier build layouts without losing all the work already done. This one unnecessary change will now require me to uninstall your mod and go back and re-build literally hours of work.

Or at the very least, give the end-user the option of selecting "Avoid Collision" or not, and let them decide. Not everybody considers these things 'cheats,' just letting people play the game each their own way they enjoy. You're already making a mod that does things the devs have not intended or built themselves yet, so you're already bending or breaking 'rules' to the game as it is. Please just allow us to use the thing to our own best enjoyment and if it concerns you that much then put the option in there for people to select and it won't allow it, otherwise just leave the mod doing what it was doing since you first released it. Thank you.

**Comment by SextonKing** [comment] 2020-10-28 12:57
Here, I want to just try and give you some real-example idea of what I'm talking about.

I *just* started this first mega-base build, my first one ever, yesterday. I designed it and discovered after getting the main base put together that the conveyor lifts for the item dispensers would be clipped by the internal walkways as you can see in the first pic. This first pic, by the way, was the last thing I did before saving and quitting the other night's session, intending to log in today and get back to work doing the rest of the lift corrections.

Normally I wouldn't be able to correct this without at least time-costly futzing with Area Actions, because trying to lay a new foundation in these spaces in order to re-lay the walkways would fail. 

But with YOUR mod the way it USED to be, I could very easily lay down a foundation by extending from the other side of the wall, then lay down a new set of walkways clipped around the conveyor lift and restore everything to functionality. CLIPPING, not CHEATING. Clipping is admitted even by the devs and many popular users of the game to be legit, even if not everybody likes the look.

Please look at these images. As in the first picture, WITH your mod the way it originally was, I could easily correct this without totally dismantling what already took some hours to refine and build. WITHOUT your mod being able to ignore collision and lay foundations in these tight spaces, I will have to now redesign and rebuild this ENTIRE complex you see in the last picture.
![Screen Shot 2020-10-28 at 8 50 35 AM](https://user-images.githubusercontent.com/72807396/97438527-4b0e0500-18fb-11eb-8ad0-b1101bcbad98.png)
![Screen Shot 2020-10-28 at 8 50 41 AM](https://user-images.githubusercontent.com/72807396/97438532-4cd7c880-18fb-11eb-80b8-bc7e3da19203.png)
![Screen Shot 2020-10-28 at 8 51 28 AM](https://user-images.githubusercontent.com/72807396/97438537-4e08f580-18fb-11eb-9c9e-b9b0f0c45c7f.png)

**Comment by Algalish** [comment] 2020-10-28 12:57
@SextonKing 
I understand that you are a bit angry about this change and don't actually mean everything that you wrote so I will not take anything  personally.

1) So, this feature will be brought back as an option in the next update. You will be able to turn it on. 
2) I did not make this discussion by myself. Several people requested it here and on discord so thats why this change happened. And I see that most of the people like it but some people need it the other way around. Sure, will try to make eveyone happy
3) **You don't need to spend any extra minute nor hour for rebuilding the base. If you remove the mod - all your foundations will still be there. The ideology of the mod is for it to be non-intrusive to the game.**  

P.S. The next update will be released within a few days but you can already use the previous version if you like. Thats easy to install it using Satisfactory Mod Manager.

**Comment by SextonKing** [comment] 2020-10-28 13:00
Thank you, none of this was meant personally of course. But in your video you called it 'cheating,' which I admit I took some offense to. And while I appreciate some other people felt differently, there is no 100% consensus to anything in this game, that's why it's so great when people give US the options to choose which way to play it. Really appreciate you hearing me out.

**Comment by SextonKing** [comment] 2020-10-28 13:01
I hope you please accept my apology for anything that came across as rude. It is actually a testament to how great a mod you've made here that it has already become so indispensable and integral to my thinking of how to approach builds in this game. I have also had a lot of real-world awfulness and "Satisfactory" has been just about my own peaceful outlet to relax, so this one change alone really threw me when I thought I'd have to re-build everything. Thanks .

**Comment by SextonKing** [comment] 2020-10-28 13:06
Just an FYI: in the Mod manager, it doesn't let you change what version to install, it only has one listed (the current one). I'm not sure if that's what you meant by being able to revert to the previous version in the manager, but that's the only option I could find and it's greyed out.

**Comment by SextonKing** [comment] 2020-10-28 13:11
NVM, found it. Thanks again.

**Comment by Algalish** [comment] 2020-10-28 13:12
@SextonKing  Its all good man, I understand.

Yes, in some of the games there are "cheaters" who make other people feel bad by making their position in game better without doing anything to gain it. But Satisfactory was never about competition so I use this word to something that changes the game process in a way that you were never able to change without mods.
So I can understand why you were offended by it and I apologize for a misunderstanding.

But what I meant by a "cheating" feature is that it REALLY changes the logic of the game. Those mods can also be amazing, but they allow you to do what you cannot do in original game. This is what I call a "cheating" feature. But not in a bad way, no.

But for Smart Foundations the goal was not to break anything. Yes, you can build foundations really quick, but the only "material" that you pay less is your own personal time. You still use concrete or other parts for other types of buildings.  

Another example is having 100 inventory slots is unacceptable to some people because they really want to struggle with less slots and play the game as intended. But some people want to have more materials with them. So everyone can play as they like here, not in a racing game when doubling your speed can imbalance the whole competition.

**Comment by Algalish** [comment] 2020-10-29 07:25
@SextonKing  I released an update but it does not bring any new features and only intended for users that are on Experimental version of the game: with pipes update. The ability to build through stuff will  be back in the next update. And it will also be only for experimental. But let me know if you are staying on normal version and not experimental and I will build a special version for you.

**Comment by SextonKing** [comment] 2020-10-29 11:17
I was planning on staying in Early Access and wait until they released the changes into that rather than all the additional bugs in Experimental. But don’t go to special trouble for me.

**Comment by SextonKing** [comment] 2020-11-13 15:37
Really excited to see when the next update comes out with the “ignore collision” ability. Truly will come in handy now that the latest stable Early Access is running. The new hotkeys for orientation are excellent.

**Comment by Algalish** [comment] 2020-11-22 06:21
@SextonKing It is finally done! In the new update you can switch this feature in settings. My appologies for this enormous delay with that feature.

**Closed by Algalish** 2020-11-22 06:21 UTC
Labels: high-priority
