### ISSUE TITLE
Adding stackable poles requires two clicks and results in slightly twisted placement

### ISSUE THREAD

**Issue by bandycj** [Algalish/SmartFoundationsPublic#28] opened 2020-10-27 21:05 UTC
When trying to add a stackable pole to an existing stack, the hologram initially lines up but after the first click it twists slightly. No matter how you rotate, it will never line up with the stack it's on.
![smart-foundations-bug](https://user-images.githubusercontent.com/165983/97361842-2750ad80-186e-11eb-8bd7-c2db7609e6d4.jpg)

**Comment by Tumblerino** [comment] 2020-10-27 21:49
I confirm this issue is also present on my game.

**Comment by Algalish** [comment] 2020-10-28 01:18
@Tumblerino  @bandycj  got it, will take care of that

**Comment by kenjura** [comment] 2020-10-30 20:13
Hi, I'm having the same issue. It's not always a slightly twist, and basically makes stackable pipes and hyperloops unusable in the current patch.

It seems like the latest patch of Smart Foundations is for the experimental build, which I guess will take several weeks to merge to Early Release. Is it possible to see a patch for this issue before then? Or should I just switch to experimental? Thanks.

**Comment by Algalish** [comment] 2020-10-31 07:45
@kenjura  Its too compicated to support both normal and experimental version now so I will probably be releasing updates only to the experimental. So I really suggest switching to experimental, since the new update brings nothing but good stuff and other mods are already updated to it - so there should not be any problems.

I cannot reproduce this bug in experimental game btw.

**Comment by Algalish** [comment] 2020-10-31 11:53
@kenjura @Tumblerino @bandycj 

I see this problem too. I always play with Options->Gameplay->"Exceute Build steps on release" on and thats why I haven't noticed that problem. I will work on a fix later today.

**Comment by Algalish** [comment] 2020-10-31 13:10
@kenjura @Tumblerino @bandycj  Can you please confirm that this bug is gone in this version? Thank you
P.S. just rename the .zip to .smod , put it into the mods folder and and dont forget to remove the existing version from there.
[Smart_Foundations-0.7.0.zip](https://github.com/Algalish/SmartFoundationsPublic/files/5469115/Smart_Foundations-0.7.0.zip)

**Comment by kenjura** [comment] 2020-10-31 22:32
The 0.7.0 version doesn't seem to have the problem in EA, although the mod itself was disabled along with a message saying it didn't work in Exp. I can also confirm that the bug isn't present in Exp with 0.6.2.

**Comment by kenjura** [comment] 2020-11-01 18:23
Spoke too soon...I can still see it in Exp with 0.6.2. I start with a stackable pipeline, which aligns normally. I put another stackable pipeline on top, which rotates out of place. Same happens with stackable hypertube supports, but stackable conveyor supports don't have the problem.

**Comment by Algalish** [comment] 2020-11-02 10:54
@kenjura  I have some urgent things in life that require my attention so I was not able to update the mod yet. But take a look at version 0.7.0 that I uploaded in my previous message: you can install it manually and stackable pipelines will work 100%.

**Comment by kenjura** [comment] 2020-11-02 20:38
No worries, not expecting anything, just wanted to give you whatever info would be helpful. I tried 0.7.0 in Exp and it seems to work just fine!

**Comment by Tumblerino** [comment] 2020-11-03 05:13
Helçp Agalish, i've tested it, removing all previous versions and the problem is still present.

**Comment by Algalish** [comment] 2020-11-03 10:32
@Tumblerino  Hey! Can you cantact me at discord Algalish#1046 so we could figure it out?
I just learned that you cannot see incoming message from people that are not in your friend list or not playing on the same server. so add me as a friend first.

**Comment by Algalish** [comment] 2020-11-11 03:19
@bandycj  @kenjura 

It is fixed in V7 and I am closing this issue. If someone can still reproduce it - please let me know with a video and steps to reproduce

**Closed by Algalish** 2020-11-11 03:19 UTC
Labels: bug
